# Generated by Django 5.1.6 on 2025-03-06 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('annual_income', models.FloatField()),
                ('monthly_expenses', models.FloatField()),
                ('savings', models.FloatField()),
                ('existing_investments', models.TextField()),
                ('risk_appetite', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('investment_goals', models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term'), ('Retirement', 'Retirement'), ('Wealth Growth', 'Wealth Growth'), ('Tax Saving', 'Tax Saving')], max_length=20)),
                ('preferred_investments', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
