# Generated by Django 5.1.6 on 2025-04-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_expense_time_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
