# Generated by Django 5.1.6 on 2025-04-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_expense_budget_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget_limit',
        ),
    ]
