# Generated by Django 5.1.6 on 2025-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('price_inr', models.FloatField()),
                ('unit', models.CharField(default='per unit', max_length=20)),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('price_inr', models.FloatField()),
                ('market_cap_inr', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('nav', models.FloatField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('aum', models.FloatField(help_text='Assets Under Management in Cr')),
                ('expense_ratio', models.FloatField()),
                ('return_1y', models.FloatField()),
                ('return_3y', models.FloatField()),
                ('return_5y', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price_inr', models.FloatField()),
                ('dividend_yield', models.FloatField()),
                ('occupancy_rate', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'symbol')},
            },
        ),
    ]
