# Generated by Django 5.1.6 on 2025-04-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_commoditydata_cryptocurrency_mutualfunddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditydata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
