# Generated by Django 5.1.6 on 2025-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_commoditydata_name_alter_commoditydata_unit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commoditydata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='price_inr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='commoditydata',
            name='unit',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='commoditydata',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_commodity_data'),
        ),
    ]
