# Generated by Django 5.1.6 on 2025-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_commoditydata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('price_inr', models.FloatField()),
                ('market_cap_inr', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('change_24h', models.FloatField()),
            ],
            options={
                'unique_together': {('name', 'symbol', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
    ]
