# Generated by Django 5.1.6 on 2025-04-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_cryptohistorydata_delete_cryptocurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutualFundData',
        ),
    ]
