# Generated by Django 5.1.6 on 2025-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_delete_mutualfunddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('nav', models.FloatField()),
                ('return_6_months', models.FloatField()),
                ('return_1_year', models.FloatField()),
                ('return_3_years', models.FloatField()),
                ('min_invest', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('sip_min_invest', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
