# Generated by Django 5.1.6 on 2025-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_mutualfunddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfunddata',
            name='return_1_year',
        ),
        migrations.RemoveField(
            model_name='mutualfunddata',
            name='return_3_years',
        ),
        migrations.RemoveField(
            model_name='mutualfunddata',
            name='return_6_months',
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='cagr_1y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='expense_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='min_invest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='sip_min_invest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
