# Generated by Django 5.1.6 on 2025-04-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_mutualfunddata_return_1_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutualFundData',
        ),
    ]
