# Generated by Django 5.1.6 on 2025-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_delete_mutualfunddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('benchmark', models.CharField(max_length=255)),
                ('nav', models.FloatField()),
                ('cagr_6m', models.FloatField(blank=True, null=True)),
                ('cagr_1y', models.FloatField(blank=True, null=True)),
                ('cagr_3y', models.FloatField(blank=True, null=True)),
                ('expense_ratio', models.FloatField(blank=True, null=True)),
                ('min_invest', models.FloatField(blank=True, null=True)),
                ('sip_min_invest', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
