# Generated by Django 5.1.6 on 2025-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_mutualfunddata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='realestatedata',
            index=models.Index(fields=['symbol'], name='dashboard_r_symbol_6a2ec5_idx'),
        ),
    ]
