# Generated by Django 5.1.6 on 2025-04-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_realestatedata_dashboard_r_symbol_6a2ec5_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealEstateData',
        ),
    ]
