# Generated by Django 5.1.6 on 2025-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_delete_mutualfunddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=50)),
                ('scheme_name', models.CharField(max_length=500)),
                ('isin_div_payout', models.CharField(blank=True, max_length=50, null=True)),
                ('isin_div_reinvestment', models.CharField(blank=True, max_length=50, null=True)),
                ('net_asset_value', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('scheme_code', 'date')},
            },
        ),
    ]
