# Generated by Django 5.1.6 on 2025-04-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_mutualfunddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutualFundData',
        ),
    ]
