# Generated by Django 5.1.6 on 2025-05-11 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_budgetlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
        migrations.AddField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
