# Generated by Django 5.1.6 on 2025-05-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
