# Generated by Django 5.1.6 on 2025-05-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
