# Generated by Django 5.1.6 on 2025-05-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_incometracker_delete_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_expenses',
        ),
    ]
