# Generated by Django 5.1.6 on 2025-05-16 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_budgetlimit_category_alter_expense_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetlimit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together={('user', 'category')},
        ),
    ]
