# Generated by Django 5.1.6 on 2025-05-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_expenseactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseactivitylog',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
