# Generated by Django 5.1.6 on 2025-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_expenseactivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='existing_investments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='savings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
