# Generated by Django 5.1.6 on 2025-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_userprofile_existing_investments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlimit',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=10),
        ),
    ]
