# Generated by Django 5.1.6 on 2025-05-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_userprofilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfilePhoto',
        ),
    ]
