# Generated by Django 5.1.6 on 2025-05-31 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_expense_date_remove_expense_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometracker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incometracker',
            name='time',
        ),
        migrations.AddField(
            model_name='budgetlimit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incometracker',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
