# Generated by Django 5.1.6 on 2025-05-31 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_remove_incometracker_date_remove_incometracker_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetlimit',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='incometracker',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incometracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incometracker',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
