# Generated by Django 5.1.6 on 2025-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_remove_expense_date_remove_expense_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseactivitylog',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Removed', 'Removed'), ('Updated', 'Updated')], max_length=10),
        ),
    ]
