# Generated by Django 5.1.6 on 2025-06-01 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_expenseactivitylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometracker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incometracker',
            name='time',
        ),
        migrations.AddField(
            model_name='incometracker',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
