# Generated by Django 5.1.6 on 2025-06-01 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_remove_incometracker_date_remove_incometracker_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='incometracker',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incometracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incometracker',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenseactivitylog',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
