# Generated by Django 5.1.6 on 2025-06-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_remove_expense_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseactivitylog',
            name='timestamp',
        ),
    ]
