# Generated by Django 5.1.6 on 2025-06-02 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_remove_expenseactivitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseactivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
