# Generated by Django 5.1.10 on 2025-06-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0064_investment_savings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenseactivitylog",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
