# Generated by Django 5.1.6 on 2025-05-08 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='massage',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
