# Generated by Django 5.1.6 on 2025-05-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
